name: mobile
description: "Wathiq mobile application."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # ─────────────────────────────────────────────
  # Flutter Localization
  # ─────────────────────────────────────────────
  flutter_localizations:
    sdk: flutter

  # ─────────────────────────────────────────────
  # iOS-style Icons
  # ─────────────────────────────────────────────
  cupertino_icons: ^1.0.8

  # ─────────────────────────────────────────────
  # Fonts
  # ─────────────────────────────────────────────
  google_fonts: ^6.3.2

  # ─────────────────────────────────────────────
  # SVG Images
  # ─────────────────────────────────────────────
  flutter_svg: ^2.2.1

  # ─────────────────────────────────────────────
  # Networking
  # ─────────────────────────────────────────────
  dio: ^5.9.0

  # ─────────────────────────────────────────────
  # Routing
  # ─────────────────────────────────────────────
  go_router: ^16.2.0

  # ─────────────────────────────────────────────
  # Routing
  # ─────────────────────────────────────────────
  pinput: ^6.0.2
  device_preview: ^1.2.0

  # ─────────────────────────────────────────────
  # State Management
  # ─────────────────────────────────────────────
  flutter_bloc: ^9.1.1

  # ─────────────────────────────────────────────
  # Responsive UI
  # ─────────────────────────────────────────────
  flutter_screenutil: ^5.9.3

  # ─────────────────────────────────────────────
  # Localization / Formatting
  # ─────────────────────────────────────────────
  intl: ^0.20.2

  country_code_picker: ^3.4.1
  image_picker: ^1.2.3
  file_picker: ^12.2.0
  image_picker2_plus: ^1.0.2
  dotted_border: ^3.1.0
  lottie: ^3.5.1
  flutter_secure_storage: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # ─────────────────────────────────────────────
  # Localization Code Generation
  # ─────────────────────────────────────────────
  generate: true

  # ─────────────────────────────────────────────
  # Assets
  # ─────────────────────────────────────────────
  assets:
    - assets/images/
    - assets/svg/
    - assets/lottie_json/
